USWDS-Sandbox - Zombie test form: Replace form links with buttons
uswds/uswds-sandbox pull request #118
Opened 2023-10-24 15:24 UTC by mahoneycm

# Summary

Replace next step links with actual buttons. 

Change made a result of our Usability testing [findings](https://github.com/uswds/uswds/issues/5527).

## Related issue

Closes #113

## Related pull requests

> **Warning**
Work should be merged after #103
> 

## Preview link

Zombie test form →

## Problem statement

Buttons within forms should be actual buttons and not links styled as buttons as stated by our [button guidance](https://designsystem.digital.gov/components/button/).

## Solution

Replace all form links styled as buttons with actual buttons. 

Buttons navigate to new pages via `onclick="location.href = '/page-destination'`

## Testing and review

1. Navigate through test form with and without screen reader.
2. Confirm the next and previous page buttons work as expected.
3. Confirm screen reader callouts are accurate.
4. Confirm screen readers are able to target the buttons using button shortcuts.
    - There doesn’t appear to be a shortcut for VoiceOver
    - For JAWs and NVDA this is `b` **********(forwards)********** or `shift + b` ***********(backwards)***********

### Testing checklist

- [ ]  Form navigates as expected
- [ ]  No visual regression
- [ ]  Screen readers call out buttons as expected
- [ ]  Screen reader navigation works as expected
- [ ]  Confirm this is the proper method to navigate through a form with buttons

2023-10-24 19:08 UTC, amycole501 reviewed
The "Sign in" button is now coded as a button so that's awesome! The "show/hide password" is styled as a link but it's functionally a button as is the "here's how you know" "button" at the top of the page in the banner. Both look like links but are actually buttons. Could prove confusing to someone who is using a screen reader to find all the links on a page and instead find a button.

2023-11-28 14:33 UTC, mejiaj requested changes
@mahoneycm none of the links seem to work in cloud pages previews. Added comment for possible fix.

2023-11-28 14:33 UTC, mejiaj commented on src/confirm-submission.html
> +            <button onclick="location.href = '/instructor-details'" class="usa-button usa-button--outline margin-y-4" type="submit">Go back to instructor details</button>
@mahoneycm this fails in preview, but you could use something like `window.location.host` to ensure the right base URL gets used in all environments.

**Steps to reproduce**
1. Go to [homepage](https://federalist-d5e7c07c-6ffa-4b8e-935f-49a7df24a505.sites.pages.cloud.gov/preview/uswds/uswds-sandbox/cm-zombie-defense-update-buttons/).
2. Click `Sign in` button.
3. Cloud pages 404 appears.

2023-11-28 19:41 UTC, mahoneycm commented
@mejiaj  thanks for catching that! I was able to resolve by returning the [11ty URL filter](https://www.11ty.dev/docs/filters/url/).

I considered using the `<path>` plugin and prefix it mentions on that page, but since the branch name will change I figured this is a better pattern for now.

2023-11-29 17:50 UTC, mejiaj approved these changes
Good fix. Confirming all links work in preview.

@mahoneycm can you get a PR approval from either @amycole501 or @alex-hull? We can merge after.

2023-12-01 14:58 UTC, amycole501 approved these changes

2023-12-01 15:03 UTC, merged